// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgsCX9Dk3-Ys05OZnIpnHy09jCWDATkjo',
    appId: '1:322167248889:web:cb5f411a2de20967334f28',
    messagingSenderId: '322167248889',
    projectId: 'recipe-f3970',
    authDomain: 'recipe-f3970.firebaseapp.com',
    storageBucket: 'recipe-f3970.firebasestorage.app',
    measurementId: 'G-KH1LM91HTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSDyVyriC7oBYQjCv0XUPeevJ86v-3P08',
    appId: '1:322167248889:android:c9a3a0b12e93cbbe334f28',
    messagingSenderId: '322167248889',
    projectId: 'recipe-f3970',
    storageBucket: 'recipe-f3970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8c9M7ugJM0JBvhFRgS-DYnqkgJRWQ48k',
    appId: '1:322167248889:ios:441594a20665498b334f28',
    messagingSenderId: '322167248889',
    projectId: 'recipe-f3970',
    storageBucket: 'recipe-f3970.firebasestorage.app',
    iosBundleId: 'com.example.foodRecepi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8c9M7ugJM0JBvhFRgS-DYnqkgJRWQ48k',
    appId: '1:322167248889:ios:441594a20665498b334f28',
    messagingSenderId: '322167248889',
    projectId: 'recipe-f3970',
    storageBucket: 'recipe-f3970.firebasestorage.app',
    iosBundleId: 'com.example.foodRecepi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgsCX9Dk3-Ys05OZnIpnHy09jCWDATkjo',
    appId: '1:322167248889:web:665580413d1a20b7334f28',
    messagingSenderId: '322167248889',
    projectId: 'recipe-f3970',
    authDomain: 'recipe-f3970.firebaseapp.com',
    storageBucket: 'recipe-f3970.firebasestorage.app',
    measurementId: 'G-51394J8912',
  );
}
